Repository rhpit/manageiq-cli, pull requests merged in 2018-03, with the labels that each got.

#125 initial documentation structure for cli usage
  doc/source/conf.py
  doc/source/contribute.rst
  doc/source/index.rst
  doc/source/introduction.rst
  doc/source/providers/amazon.rst
  doc/source/providers/openstack.rst
  doc/source/quickstart.rst
  test-requirements.txt
Labels: documentation

#126 document the client installation procedure
  doc/source/installation.rst
Labels: documentation

#127 document the client create and delete openstack provider
  doc/source/providers/openstack.rst
Labels: documentation

#128 document the client create and delete amazon provider
  doc/source/providers/amazon.rst
Labels: documentation

#132 Amazon provision and teardown resources doc
  doc/source/providers/amazon.rst
  example/aws_deletion_example.py
  example/aws_provision_example.py
Labels: documentation

#136 fix testinstance script compatibility with python 3.6
  scripts/testinstance
Labels: bug

#137 add warning if etc config directory does not exist
  miqcli/utils/__init__.py
Labels: bug

#138 document the client for declaring server configuration settings
  doc/source/configuration.rst
  doc/source/quickstart.rst
  example/config/config_token.yml
  example/config/config_userpasswd.yml
  example/miqcli.yaml
Labels: documentation

#139 remove static code blocks for creating and deleting providers
  doc/source/providers/amazon.rst
  doc/source/providers/openstack.rst
Labels: documentation

#140 Documenation for OpenStack VM creation and deletion
  doc/source/providers/openstack.rst
  example/openstack_provision_ex.json
  miqcli/constants.py
Labels: documentation

#141 update client class loading server configuration
  example/aws_deletion_example.py
  example/aws_provision_example.py
  example/osp_deletion_example.py
  example/osp_provision_example.py
  example/providers/amazon/create.py
  example/providers/amazon/delete.py
  example/providers/amazon/refresh.py
  example/providers/openstack/create.py
  example/providers/openstack/delete.py
  example/providers/openstack/refresh.py
  miqcli/api.py
  miqcli/utils/__init__.py
Labels: enhancement

#144 add integration test case to validate commands list
  .gitignore
  tests/assets/integration_config.yml
  tests/integration/test_collections.py
  tox.ini
Labels: tests

#145 updating docs to have a configuration validation section
  doc/source/configuration.rst
  miqcli/collections/zones.py
Labels: documentation, enhancement
