Repository rhpit/manageiq-cli, pull requests merged in 2018-02, with the labels that each got.

#100 fix config load from yaml when the yaml file is wrong
  miqcli/utils/__init__.py
Labels: bug

#104 add issue template for project
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#105 add a pull request template for the project
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#106 catch syntax error when loading config from environment
  miqcli/utils/__init__.py
Labels: enhancement

#107 add test coverage for multiple modules
  .gitignore
  scripts/testinstance
  test-requirements.txt
  tests/assets/auth_token
  tests/assets/config.yml
  tests/assets/empty_auth_token
  tests/assets/empty_config.yml
  tests/assets/error_config.yml
  tests/assets/extrakeysonly_config.yml
  tests/assets/noformat_config.yml
  tests/functional/test_api.py
  tests/functional/test_utils.py
  tests/functional/test_utils_log.py
  tests/integration/.keep
  tox.ini
Labels: tests

#110 Adding support for multiple attributes for instance query
  example/osp_deletion_example.py
  example/osp_provision_example.py
  miqcli/collections/instances.py
Labels: enhancement
